//package hello;
//
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.GetMapping;
//import org.springframework.web.bind.annotation.RequestParam;
//import org.springframework.web.bind.annotation.ResponseBody;
//
//import java.util.Optional;
//
//@Controller    // This means that this class is a Controller
//@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
//public class CustomController {
//    @Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private UserRepository userRepository;
//    private UserRepository2 userRepository2;
//    @GetMapping(path = "/all")
//    public @ResponseBody
//    String getCustomFeed(@RequestParam String f) {
//        // This returns a JSON or XML with the users
//
//        return (UserRepository)f;
//    }
//}
